import { describe, test, expect } from "bun:test";
import { parsePRIssueNumber } from "../../src/commands/fix-pr";

describe("parsePRIssueNumber", () => {
  test("parses 'fixes #NNN'", () => {
    const body = "## Summary\n\nAutomatically fixes #42.\n\n🤖 Generated by flogvit-pilot";
    expect(parsePRIssueNumber(body)).toBe(42);
  });

  test("parses 'closes #NNN'", () => {
    const body = "This PR closes #123.";
    expect(parsePRIssueNumber(body)).toBe(123);
  });

  test("parses 'resolves #NNN'", () => {
    const body = "resolves #7";
    expect(parsePRIssueNumber(body)).toBe(7);
  });

  test("is case insensitive", () => {
    const body = "Fixes #55";
    expect(parsePRIssueNumber(body)).toBe(55);
  });

  test("returns null when no issue link found", () => {
    const body = "No issue link here";
    expect(parsePRIssueNumber(body)).toBeNull();
  });
});
